version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.8
    container_name: clickhouse
    ports:
      - "8123:8123"  # HTTP port
      - "9000:9000"  # TCP port
    volumes:
      - ./config/config.xml:/etc/clickhouse-server/config.xml      
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - ./ch_data:/var/lib/clickhouse
      - ./ch_logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: always
